			// PKL
			{"bludriver","LDirtEffects"},
			{"bludjungle1","LDirtEffects"},
			{"bludjungle2","LDirtEffects"},
			{"bludjungle3","LDirtEffects"},
			{"bludgressj","LDirtEffects"},
			{"bludgressj","LDustEffects"},
			{"bludgressj","LGrassEffects"},
			{"bludjunglerd1","LDirtEffects"},
			{"bludjunglerd1","LDustEffects"},
			{"bludjunglerd2","LDirtEffects"},
			{"bludjunglerd2","LDustEffects"},
			{"bludrivermaling","LDirtEffects"},
			{"bludrivermaling","LDustEffects"},
			{"blud_sti","LDirtEffects"},
			{"blud_sti","LDustEffects"},