			// PKL
			{"bludriver","RDustEffectsMan"},
			{"bludjungle1","RDustEffectsMan"},
			{"bludjungle2","RDustEffectsMan"},
			{"bludjungle3","RDustEffectsMan"},
			{"bludgressj","RDustEffectsMan"},
			{"bludjunglerd1","RDustEffectsMan"},
			{"bludjunglerd2","RDustEffectsMan"},
			{"bludrivermaling","RDustEffectsMan"},
			{"blud_sti","RDustEffectsMan"},