			// Fallujah
			{"siFallujahTerra","LDustEffectsMan"},
			{"siFallujahAcqua","LDustEffectsMan"},
			{"siFallujahErba","LDustEffectsMan"},
			{"siFallujahSabbia","LDustEffectsMan"},
			{"siFallujahCitta","LDustEffectsMan"},
			// Aliabad
			{"AliDirtSurface","LDustEffectsMan"},
			{"AliSandSurface","LDustEffectsMan"},
			{"AliDesertSurface","LDustEffectsMan"},
			{"AliForestSurface","LDustEffectsMan"},
			{"AliRockySurface","LDustEffectsMan"},
			{"AliCliffSurface","LDustEffectsMan"},
			{"AliRiverbedSurface","LDustEffectsMan"},
			// HazarKot
			{"FTDirtSurface","LDustEffectsMan"},
			{"FTSandSurface","LDustEffectsMan"},
			{"FTDesertSurface","LDustEffectsMan"},
			{"FTForestSurface","LDustEffectsMan"},
			{"FTRockySurface","LDustEffectsMan"},
			// Caribou
			{"CARIBOU_FOREST01","LDustEffectsMan"},
			{"CARIBOU_FOREST02","LDustEffectsMan"},
			{"CARIBOU_GRASS01","LDustEffectsMan"},
			{"CARIBOU_GRASS02","LDustEffectsMan"},
			{"CARIBOU_GRAVEL01","LDustEffectsMan"},
			{"CARIBOU_GRAVEL02","LDustEffectsMan"},
			{"CARIBOU_ROCK01","LDustEffectsMan"},
			{"CARIBOU_ROCK02","LDustEffectsMan"},
			{"CARIBOU_BETON01","LDustEffectsMan"},
			// Podagorsk
			{"FDF_Tex_1","LDustEffectsMan"},
			{"FDF_Tex_2","LDustEffectsMan"},
			{"FDF_Tex_3","LDustEffectsMan"},
			{"FDF_Tex_4","LDustEffectsMan"},
			{"FDF_Tex_5","LDustEffectsMan"},
			{"FDF_Tex_6","LDustEffectsMan"},
			{"FDF_Tex_7","LDustEffectsMan"},
			{"FDF_Tex_8","LDustEffectsMan"},
			{"FDF_Tex_9","LDustEffectsMan"},
			{"FDF_Tex_10","LDustEffectsMan"},
			{"FDF_Tex_11","LDustEffectsMan"},
			// Zernovo
			{"gsep_creekbedsurface","LDustEffectsMan"},
			{"gsepconcretegroundsurface","LDustEffectsMan"},
			{"gsepdirtsurface","LDustEffectsMan"},
			{"gsepforest1surface","LDustEffectsMan"},
			{"gseptallgrasssurface","LDustEffectsMan"},
			{"gsepshortgrasssurface","LDustEffectsMan"},
			{"gsepbarerocksurface","LDustEffectsMan"},
			{"gsepgravelsurface","LDustEffectsMan"},
			{"gsephayfieldsurface","LDustEffectsMan"},
			{"gsepcropsurface","LDustEffectsMan"},
			// Thirsk
			{"THgrass2","LDustEffectsMan"},
			{"THgrass3","LDustEffectsMan"},
			{"THForest1","LDustEffectsMan"},
			{"THForest2","LDustEffectsMan"},
			{"THGrit1","LDustEffectsMan"},
			{"THBetoni1","LDustEffectsMan"},
			{"THRock","LDustEffectsMan"},
			{"THTarmac","LDustEffectsMan"},